name: Manual workflow
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  check-command:
    runs-on: ubuntu-20.04
    environment: test
    env:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
    steps:
    - name: Check environment
      run: |
        whoami
        pwd
        ls -al
        which oc
        oc version
        env | sort
    - name: Determine app name
      if: env.APP_NAME == ''
      run: |
        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
    - name: Log in to OpenShift
      run: |
        oc login \
          --token "${{ secrets.OPENSHIFT_TOKEN }}" \
          --insecure-skip-tls-verify \
          ${{ env.OPENSHIFT_SERVER }}
#      uses: redhat-actions/oc-login@v1
#      with:
#        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
#        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
#        insecure_skip_tls_verify: true
#        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Create Project if not exists
      run: |
        if ! oc project ${{ env.OPENSHIFT_NAMESPACE }} ; then
          oc new-project ${{ env.OPENSHIFT_NAMESPACE }}
        fi
    - name: Create ImageStream if not exists
      run: |
        if ! oc get is jboss-eap73-openjdk11-openshift ; then
          oc replace --force -f \
            https://raw.githubusercontent.com/jboss-container-images/jboss-eap-7-openshift-image/7.3.x/templates/eap73-openjdk11-image-stream.json
        fi
    - name: Create Template if not exists
      run: |
        if ! oc get template eap73-openjdk11-basic-s2i ; then
          oc replace --force -f \
            https://raw.githubusercontent.com/jboss-container-images/jboss-eap-7-openshift-image/7.3.x/templates/eap73-openjdk11-basic-s2i.json
        fi
    - name: Last
      run: |
        oc whoami
        oc status
        oc get all
